name: Destroy pre-signed URL Resources

on:
  workflow_dispatch: # manually run

permissions:
  id-token: write
  contents: read


jobs:
  terraform-destroy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.0"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1

      - name: Create dummy zip for destroy
        run: touch lambda.zip

      - name: Terraform Destroy
        run: |
          terraform init
          terraform destroy -auto-approve

